## MACRO
TARGET = bulletml.exe
MAKE = make
MAKEFILE = Makefile
TO_COMPILE = src\sworks\bulletml\ctbml.d src\sworks\compo\util\matrix.d src\sworks\compo\sdl\port.d src\sworks\compo\gl\port.d src\sworks\compo\sdl\gl.d src\sworks\compo\gl\texture_2drgba32.d src\sworks\compo\util\dump_members.d src\sworks\compo\sdl\util.d src\sworks\compo\gl\util.d src\sworks\compo\gl\glsl.d src\sworks\compo\util\factory.d src\sworks\compo\sdl\image.d
TO_LINK = src\sworks\bulletml\ctbml.obj src\sworks\compo\util\matrix.obj src\sworks\compo\sdl\port.obj src\sworks\compo\gl\port.obj src\sworks\compo\sdl\gl.obj src\sworks\compo\gl\texture_2drgba32.obj src\sworks\compo\util\dump_members.obj src\sworks\compo\sdl\util.obj src\sworks\compo\gl\util.obj src\sworks\compo\gl\glsl.obj src\sworks\compo\util\factory.obj src\sworks\compo\sdl\image.obj
COMPILE_FLAG = -debug=bulletml -Jsample -version=Unicode -version=WindowsVista -Isrc;import
LINK_FLAG =
EXT_LIB = lib\DerelictGL3.lib lib\DerelictSDL2.lib lib\DerelictUtil.lib
DDOC_FILE = doc\main.ddoc
FLAG =

## LINK COMMAND
$(TARGET) : $(TO_LINK) $(EXT_LIB)
	dmd -g $(LINK_FLAG) $(FLAG) -of$@ $**

## COMPILE RULE
.d.obj :
	dmd -c -g -op -debug $(COMPILE_FLAG) $(FLAG) $<

## DEPENDENCE
$(TO_LINK) : $(MAKEFILE) $(EXT_LIB)
src\sworks\bulletml\ctbml.obj : src\sworks\bulletml\ctbml.d src\sworks\compo\util\matrix.d src\sworks\compo\sdl\port.d src\sworks\compo\sdl\gl.d src\sworks\compo\gl\port.d src\sworks\compo\gl\texture_2drgba32.d src\sworks\compo\util\dump_members.d src\sworks\compo\sdl\util.d src\sworks\compo\gl\util.d src\sworks\compo\gl\glsl.d src\sworks\compo\util\factory.d src\sworks\compo\sdl\image.d
src\sworks\compo\util\matrix.obj : src\sworks\compo\util\matrix.d
src\sworks\compo\sdl\port.obj : src\sworks\compo\sdl\port.d
src\sworks\compo\gl\port.obj : src\sworks\compo\gl\port.d
src\sworks\compo\sdl\gl.obj : src\sworks\compo\sdl\gl.d src\sworks\compo\gl\port.d src\sworks\compo\gl\texture_2drgba32.d src\sworks\compo\sdl\port.d src\sworks\compo\gl\util.d src\sworks\compo\gl\glsl.d src\sworks\compo\sdl\util.d src\sworks\compo\sdl\image.d
src\sworks\compo\gl\texture_2drgba32.obj : src\sworks\compo\gl\texture_2drgba32.d src\sworks\compo\gl\port.d
src\sworks\compo\util\dump_members.obj : src\sworks\compo\util\dump_members.d
src\sworks\compo\sdl\util.obj : src\sworks\compo\sdl\port.d src\sworks\compo\sdl\util.d
src\sworks\compo\gl\util.obj : src\sworks\compo\gl\port.d src\sworks\compo\gl\util.d
src\sworks\compo\gl\glsl.obj : src\sworks\compo\gl\port.d src\sworks\compo\gl\glsl.d src\sworks\compo\gl\util.d
src\sworks\compo\util\factory.obj : src\sworks\compo\util\factory.d
src\sworks\compo\sdl\image.obj : src\sworks\compo\sdl\port.d src\sworks\compo\sdl\util.d src\sworks\compo\sdl\image.d

## PHONY TARGET
debug-all :
	dmd -g -debug -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB)  $(FLAG)
release :
	dmd -release -O -inline -L/exet:nt/su:windows:6.0 -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB)  $(FLAG)
clean :
	del $(TARGET) $(TO_LINK)
clean_obj :
	del $(TO_LINK)
vwrite :
	vwrite -ver="0.0002(dmd2.060)" -prj=$(TARGET) $(TO_COMPILE)
ddoc :
	dmd -c -o- -op -D -Dddoc $(COMPILE_FLAG) $(DDOC_FILE) $(TO_COMPILE) $(FLAG)
show :
	@echo ROOT = src\sworks\bulletml\ctbml.d
	@echo TARGET = $(TARGET)
	@echo VERSION = 0.0002(dmd2.060)
run :
	$(TARGET) $(FLAG)
edit :
	emacs $(TO_COMPILE)  Makefile
remake :
	amm gui -debug=bulletml -Jsample vwrite=0.0002(dmd2.060) .\src\sworks\bulletml\ctbml.d .\doc\main.ddoc $(FLAG)

debug :
	ddbg $(TARGET)

## generated by amm.