## for gnu make
## DOT DIRECTIVE
.PHONY : release clean show remake install run edit clean_obj vwrite debug-all ddoc
## MACRO
TARGET = ctbml
AUTHORS =
LICENSE =
VERSION =

MAKEFILE = Makefile
DC = dmd
MAKE = gmake
TO_COMPILE = src/sworks/base/aio.d src/sworks/gl/port.d src/sworks/base/dump_members.d src/sworks/bulletml/ctbml.d src/sworks/base/ctfe.d src/sworks/gl/texture_2drgba32.d src/sworks/sdl/util.d src/sworks/base/factory.d src/sworks/base/matrix.d src/sworks/gl/bo.d src/sworks/gl/glsl.d src/sworks/gl/util.d src/sworks/sdl/gl.d src/sworks/xml.d src/sworks/util/cached_buffer.d src/sworks/sdl/image.d src/sworks/sdl/port.d
TO_LINK = src/sworks/base/aio.o src/sworks/gl/port.o src/sworks/base/dump_members.o src/sworks/bulletml/ctbml.o src/sworks/base/ctfe.o src/sworks/gl/texture_2drgba32.o src/sworks/sdl/util.o src/sworks/base/factory.o src/sworks/base/matrix.o src/sworks/gl/bo.o src/sworks/gl/glsl.o src/sworks/gl/util.o src/sworks/sdl/gl.o src/sworks/xml.o src/sworks/util/cached_buffer.o src/sworks/sdl/image.o src/sworks/sdl/port.o
COMPILE_FLAG = -Jsample -debug=bulletml -Isrc:/usr/local/include
LINK_FLAG = -L-lDerelictUtil -L-lDerelictSDL2 -L-lDerelictGL3
EXT_LIB =
DDOC_FILE =
FLAG =

## LINK COMMAND
$(TARGET) : $(TO_LINK) $(EXT_LIB)
	$(DC) -g -of$@ $(LINK_FLAG) $(TO_LINK) $(EXT_LIB) $(FLAG)

## COMPILE RULE
%.o : %.d
	$(DC) -c -g -op -debug $(COMPILE_FLAG) $(FLAG) $<

## DEPENDENCE
$(TO_LINK) : $(MAKEFILE) $(EXT_LIB)
src/sworks/base/aio.o : src/sworks/base/aio.d
src/sworks/gl/port.o : src/sworks/gl/port.d
src/sworks/base/dump_members.o : src/sworks/base/dump_members.d
src/sworks/bulletml/ctbml.o : src/sworks/base/aio.d src/sworks/gl/port.d src/sworks/base/dump_members.d src/sworks/bulletml/ctbml.d src/sworks/base/ctfe.d src/sworks/gl/texture_2drgba32.d src/sworks/sdl/util.d src/sworks/base/factory.d src/sworks/base/matrix.d src/sworks/gl/bo.d src/sworks/gl/glsl.d src/sworks/sdl/gl.d src/sworks/gl/util.d src/sworks/xml.d src/sworks/util/cached_buffer.d src/sworks/sdl/image.d src/sworks/sdl/port.d
src/sworks/base/ctfe.o : src/sworks/base/ctfe.d
src/sworks/gl/texture_2drgba32.o : src/sworks/gl/port.d src/sworks/gl/texture_2drgba32.d
src/sworks/sdl/util.o : src/sworks/util/cached_buffer.d src/sworks/sdl/util.d src/sworks/base/aio.d src/sworks/sdl/port.d
src/sworks/base/factory.o : src/sworks/base/factory.d
src/sworks/base/matrix.o : src/sworks/base/matrix.d
src/sworks/gl/bo.o : src/sworks/gl/bo.d src/sworks/gl/port.d
src/sworks/gl/glsl.o : src/sworks/util/cached_buffer.d src/sworks/gl/glsl.d src/sworks/gl/bo.d src/sworks/base/aio.d src/sworks/gl/port.d
src/sworks/gl/util.o : src/sworks/gl/port.d src/sworks/base/aio.d src/sworks/gl/glsl.d src/sworks/base/matrix.d src/sworks/gl/bo.d src/sworks/gl/util.d src/sworks/util/cached_buffer.d
src/sworks/sdl/gl.o : src/sworks/gl/port.d src/sworks/base/aio.d src/sworks/gl/glsl.d src/sworks/gl/texture_2drgba32.d src/sworks/sdl/util.d src/sworks/base/matrix.d src/sworks/gl/bo.d src/sworks/sdl/gl.d src/sworks/gl/util.d src/sworks/util/cached_buffer.d src/sworks/sdl/image.d src/sworks/sdl/port.d
src/sworks/xml.o : src/sworks/xml.d src/sworks/util/cached_buffer.d src/sworks/base/aio.d src/sworks/base/ctfe.d
src/sworks/util/cached_buffer.o : src/sworks/util/cached_buffer.d src/sworks/base/aio.d
src/sworks/sdl/image.o : src/sworks/sdl/image.d src/sworks/sdl/util.d src/sworks/util/cached_buffer.d src/sworks/sdl/port.d src/sworks/base/aio.d
src/sworks/sdl/port.o : src/sworks/sdl/port.d

## PHONY TARGET
debug-all :
	$(DC) -g -debug -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB)  $(FLAG)
release :
	$(DC) -release -O -inline -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB)  $(FLAG)
clean :
	rm $(TARGET) $(TO_LINK)
clean_obj :
	rm $(TO_LINK)
vwrite :
	vwrite --setversion "$(VERSION)" --project "$(TARGET)" --authors "$(AUTHORS)" --license "$(LICENSE)" $(TO_COMPILE)
ddoc :
	$(DC) -c -o- -op -D -Dddoc $(COMPILE_FLAG) $(DDOC_FILE) $(TO_COMPILE) $(FLAG)
show :
	@echo ROOT = src/sworks/bulletml/ctbml.d
	@echo TARGET = $(TARGET)
	@echo VERSION =
edit :
	emacs $(TO_COMPILE)
remake :
	amm imp=/usr/local/include -Jsample -debug=bulletml src/sworks/bulletml/ctbml.d -L-lDerelictUtil -L-lDerelictSDL2 -L-lDerelictGL3 $(FLAG)

debug :
	ddbg $(TARGET)

## generated by amm.
